Repository citizenlab/test-lists, pull requests merged in 2022-01, with the labels that each got.

#820 bd.csv list, Follow on from #809
  lists/bd.csv
Labels: ci-failing

#812 Add Facebook CDN domains
  lists/global.csv
Labels: ci-failing

#661 Updated several lists with reproduction rights sites
  lists/id.csv
  lists/kr.csv
  lists/my.csv
  lists/pl.csv
  lists/sa.csv
  lists/tr.csv
Labels: needs-conflict-resolution

#725 Add Daily Stormer
  lists/global.csv
Labels: needs-conflict-resolution

#697 update vn.csv
  lists/vn.csv
Labels: feedback-required

#718 Patch 3
  lists/tr.csv
Labels: feedback-required

#446 Add Tor directory authorities server descriptors
  lists/global.csv
Labels: feedback-required

#716 Proposed updates to Uganda test list to include regional and global news sites
  lists/ug.csv
Labels: feedback-required

#715 Update global.csv
  lists/global.csv
Labels: feedback-required

#695 Update global.csv
  lists/global.csv
Labels: feedback-required

#726 Add Library Genesis URLs
  lists/fr.csv
  lists/global.csv
Labels: needs-conflict-resolution
